name: Deploy To Staging

on:
  push:
    branches:
      - CU-t79dbn_Revamp-reset-password

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.11.10 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "chatterus-stage" #Must be unique in Heroku
          heroku_email: "hua.dylan@gmail.com"